// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scaphoid.Infrastructure.Data;

#nullable disable

namespace Scaphoid.Migrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230413141111_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Scaphoid.Core.Model.Beam", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BottomFlangeThickness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BottomFlangeWidth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUniformDepth")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Span")
                        .HasColumnType("REAL");

                    b.Property<int>("TopFlangeThickness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopFlangeWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WebDepth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WebDepthRight")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WebThickness")
                        .HasColumnType("REAL");

                    b.HasKey("OrderId");

                    b.ToTable("Beam");
                });

            modelBuilder.Entity("Scaphoid.Core.Model.Loading", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoadType")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderId");

                    b.ToTable("Loading");
                });

            modelBuilder.Entity("Scaphoid.Core.Model.Localization", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DesignType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PsiValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ULSLoadExpression")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderId");

                    b.ToTable("Localization");
                });

            modelBuilder.Entity("Scaphoid.Core.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beam")
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<string>("Designer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Project")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Scaphoid.Core.Model.PointLoad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Load")
                        .HasColumnType("REAL");

                    b.Property<int>("LoadingId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Position")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LoadingId");

                    b.ToTable("PointLoad");
                });

            modelBuilder.Entity("Scaphoid.Core.Model.Beam", b =>
                {
                    b.HasOne("Scaphoid.Core.Model.Order", "Order")
                        .WithOne("BeamInfo")
                        .HasForeignKey("Scaphoid.Core.Model.Beam", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Scaphoid.Core.Model.Loading", b =>
                {
                    b.HasOne("Scaphoid.Core.Model.Order", "Order")
                        .WithOne("Loading")
                        .HasForeignKey("Scaphoid.Core.Model.Loading", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Scaphoid.Core.Model.LoadParameters", "PermanentLoads", b1 =>
                        {
                            b1.Property<int>("LoadingOrderId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("AxialForce")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("EndMomentLeft")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("EndMomentRight")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PartialUdl")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PartialUdlEnd")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PartialUdlStart")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Udl")
                                .HasColumnType("INTEGER");

                            b1.HasKey("LoadingOrderId");

                            b1.ToTable("Loading");

                            b1.WithOwner()
                                .HasForeignKey("LoadingOrderId");
                        });

                    b.OwnsOne("Scaphoid.Core.Model.LoadParameters", "UltimateLoads", b1 =>
                        {
                            b1.Property<int>("LoadingOrderId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("AxialForce")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("EndMomentLeft")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("EndMomentRight")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PartialUdl")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PartialUdlEnd")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PartialUdlStart")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Udl")
                                .HasColumnType("INTEGER");

                            b1.HasKey("LoadingOrderId");

                            b1.ToTable("Loading");

                            b1.WithOwner()
                                .HasForeignKey("LoadingOrderId");
                        });

                    b.OwnsOne("Scaphoid.Core.Model.LoadParameters", "VariableLoads", b1 =>
                        {
                            b1.Property<int>("LoadingOrderId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("AxialForce")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("EndMomentLeft")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("EndMomentRight")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PartialUdl")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PartialUdlEnd")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PartialUdlStart")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Udl")
                                .HasColumnType("INTEGER");

                            b1.HasKey("LoadingOrderId");

                            b1.ToTable("Loading");

                            b1.WithOwner()
                                .HasForeignKey("LoadingOrderId");
                        });

                    b.Navigation("Order");

                    b.Navigation("PermanentLoads");

                    b.Navigation("UltimateLoads");

                    b.Navigation("VariableLoads");
                });

            modelBuilder.Entity("Scaphoid.Core.Model.Localization", b =>
                {
                    b.HasOne("Scaphoid.Core.Model.Order", "Order")
                        .WithOne("Localization")
                        .HasForeignKey("Scaphoid.Core.Model.Localization", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Scaphoid.Core.Model.DeflectionLimit", "DeflectionLimit", b1 =>
                        {
                            b1.Property<int>("LocalizationOrderId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("TotalLoads")
                                .HasColumnType("REAL");

                            b1.Property<double>("VariableLoads")
                                .HasColumnType("REAL");

                            b1.HasKey("LocalizationOrderId");

                            b1.ToTable("Localization");

                            b1.WithOwner()
                                .HasForeignKey("LocalizationOrderId");
                        });

                    b.OwnsOne("Scaphoid.Core.Model.DesignParameters", "DesignParameters", b1 =>
                        {
                            b1.Property<int>("LocalizationOrderId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("GammaG")
                                .HasColumnType("REAL");

                            b1.Property<double>("GammaQ")
                                .HasColumnType("REAL");

                            b1.Property<double>("ModificationFactorAllOtherHtoB")
                                .HasColumnType("REAL");

                            b1.Property<double>("ModificationFactorKflHtoBLessThanTwo")
                                .HasColumnType("REAL");

                            b1.Property<double>("ReductionFactorF")
                                .HasColumnType("REAL");

                            b1.Property<double>("SteelGradeS235Between16and40mm")
                                .HasColumnType("REAL");

                            b1.Property<double>("SteelGradeS235Between40and63mm")
                                .HasColumnType("REAL");

                            b1.Property<double>("SteelGradeS235LessThan16mm")
                                .HasColumnType("REAL");

                            b1.Property<double>("SteelGradeS355Between16and40mm")
                                .HasColumnType("REAL");

                            b1.Property<double>("SteelGradeS355Between40and63mm")
                                .HasColumnType("REAL");

                            b1.Property<double>("SteelGradeS355LessThan16mm")
                                .HasColumnType("REAL");

                            b1.HasKey("LocalizationOrderId");

                            b1.ToTable("Localization");

                            b1.WithOwner()
                                .HasForeignKey("LocalizationOrderId");
                        });

                    b.Navigation("DeflectionLimit");

                    b.Navigation("DesignParameters");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Scaphoid.Core.Model.PointLoad", b =>
                {
                    b.HasOne("Scaphoid.Core.Model.Loading", "Loading")
                        .WithMany("PointLoads")
                        .HasForeignKey("LoadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loading");
                });

            modelBuilder.Entity("Scaphoid.Core.Model.Loading", b =>
                {
                    b.Navigation("PointLoads");
                });

            modelBuilder.Entity("Scaphoid.Core.Model.Order", b =>
                {
                    b.Navigation("BeamInfo");

                    b.Navigation("Loading");

                    b.Navigation("Localization");
                });
#pragma warning restore 612, 618
        }
    }
}
